spring.application.name=PulseCare

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/HospitalManagement
spring.datasource.username=postgres
spring.datasource.password=123

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secretKey=12345678901234567890123456789012